function [data, time] = read_data_from_txt(txt_path, chunk_size, first_line)
    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: C:\Users\User\Documents\MATLAB\CrumplingSheets\oscillation_data1.txt
    %
    % Auto-generated by MATLAB on 13-Jan-2020 12:17:33

    %% Setup the Import Options
%     chunk_size = 1e7 ;
%     first_line = 1 ;
    opts = delimitedTextImportOptions("NumVariables", 2);

    % Specify range and delimiter
    opts.DataLines = [first_line, first_line + chunk_size];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["time", "data"];
    opts.VariableTypes = ["double", "double"];
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Import the data
    % tbl = readtable("C:\Users\User\Documents\MATLAB\CrumplingSheets\oscillation_data1.txt", opts);
%     tbl = readtable("D:\Yaniv\CrumplingSheets\oscillation_data1.txt", opts);
    tbl = readtable(txt_path, opts);

    %% Convert to output type
    time = tbl.time;
    data = tbl.data;

    %% Clear temporary variables
end

